/* Net TP2_2022_IOPT_TOOLS - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */

#include <string.h>
#include "net_types.h"

#define ABS(x) (((x)>=0)?(x):-(x))

/* Array implementation: */
void createInitial_TP2_2022_IOPT_TOOLS_NetMarking( TP2_2022_IOPT_TOOLS_NetMarking* init_marking )
{
    memset( init_marking, 0, sizeof(*init_marking) );
    init_marking->p_2 = 1; /* Place p_Checking_Conditions */
    init_marking->p_7 = 0; /* Place p_Checked */
    init_marking->p_12 = 0; /* Place p_Starting_Irrigation */
    init_marking->p_23 = 0; /* Place p_Stoping_Irrigation */
    init_marking->p_56 = 0; /* Place p_Irrigating */
    init_marking->p_80 = 0; /* Place p_Irrigating_Timer */
}

void createEmpty_TP2_2022_IOPT_TOOLS_NetMarking( TP2_2022_IOPT_TOOLS_NetMarking* empty_marking )
{
    empty_marking->p_2 = 0; /* Place p_Checking_Conditions */
    empty_marking->p_7 = 0; /* Place p_Checked */
    empty_marking->p_12 = 0; /* Place p_Starting_Irrigation */
    empty_marking->p_23 = 0; /* Place p_Stoping_Irrigation */
    empty_marking->p_56 = 0; /* Place p_Irrigating */
    empty_marking->p_80 = 0; /* Place p_Irrigating_Timer */
}

void add_TP2_2022_IOPT_TOOLS_NetMarkings(
    TP2_2022_IOPT_TOOLS_NetMarking* dest_marking,
    TP2_2022_IOPT_TOOLS_NetMarking* source_marking )
{
    dest_marking->p_2 += source_marking->p_2; /* Place p_Checking_Conditions */
    dest_marking->p_7 += source_marking->p_7; /* Place p_Checked */
    dest_marking->p_12 += source_marking->p_12; /* Place p_Starting_Irrigation */
    dest_marking->p_23 += source_marking->p_23; /* Place p_Stoping_Irrigation */
    dest_marking->p_56 += source_marking->p_56; /* Place p_Irrigating */
    dest_marking->p_80 += source_marking->p_80; /* Place p_Irrigating_Timer */
}

void init_TP2_2022_IOPT_TOOLS_OutputSignals(
    TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
    TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    memset( place_out, 0, sizeof(*place_out) );
    memset( ev_out, 0, sizeof(*ev_out) );
    ev_out->os_Irrigation = 0;
    place_out->os_Irrigation_Duration = 0;
    place_out->os_Sensor_Check = 0;
}

/* Transition 3 - t_Check_Humidity */
int t_3_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_3_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_3_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( ( inputs->is_Humidity_Soil <= 25 && inputs->is_Humidity_Air <= 60 && inputs->is_Meteo_Station_Rain <= 40 ) && inputs->is_Override_Irrigation == 0 );
}

void t_3_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2--;
}

void t_3_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_7++;
}

void t_3_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 13 - t_Stop_Irrigation */
int t_13_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_23 >= 1 );
}

int t_13_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_13_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_13_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_23--;
}

void t_13_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2++;
}

void t_13_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
    ev_out->oe_Irrigation_Off = 1;
}


/* Transition 20 - t_Irrigation_Check */
int t_20_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_56 >= 1 );
}

int t_20_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_20_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( place_out->os_Irrigation_Duration == 5 && inputs->is_Override_Irrigation == 0 );
}

void t_20_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_56--;
}

void t_20_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_80++;
}

void t_20_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 59 - t_Open_Valves */
int t_59_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_12 >= 1 );
}

int t_59_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_59_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_59_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_12--;
}

void t_59_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_56++;
}

void t_59_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 62 - t_Check_Rain */
int t_62_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_62_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_62_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( inputs->is_Meteo_Station_Rain < 40 && inputs->is_Override_Irrigation == 0 );
}

void t_62_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2--;
}

void t_62_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_7++;
}

void t_62_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 78 - t_Override_On */
int t_78_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( 1 );
}

int t_78_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return ( events->ie_Override_Irrigation_On );
}

int t_78_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_78_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
}

void t_78_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
}

void t_78_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 79 - t_Override_Off */
int t_79_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( 1 );
}

int t_79_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return ( events->ie_Override_Irrigation_Off );
}

int t_79_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_79_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
}

void t_79_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
}

void t_79_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 81 - t_Close_Valves */
int t_81_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_81_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_81_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( ev_out->os_Irrigation == 1 );
}

void t_81_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2--;
}

void t_81_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_23++;
}

void t_81_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 85 - t_Start_Irrigation_by_Sensors */
int t_85_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_7 >= 1 );
}

int t_85_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_85_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_85_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_7--;
}

void t_85_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_12++;
}

void t_85_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
    ev_out->oe_Irrigation_On = 1;
}


/* Transition 89 - t_Go_Check */
int t_89_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_80 >= 1 );
}

int t_89_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_89_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return (  1  );
}

void t_89_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_80--;
}

void t_89_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2++;
}

void t_89_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 103 - t_Irrigation_Override_Off */
int t_103_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_56 >= 1 );
}

int t_103_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_103_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( inputs->is_Override_Irrigation == 0 && place_out->os_Sensor_Check == 0 );
}

void t_103_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_56--;
}

void t_103_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2++;
}

void t_103_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
}


/* Transition 112 - t_Start_Irrigation_by_Override */
int t_112_enabled( TP2_2022_IOPT_TOOLS_NetMarking* prev,
                    TP2_2022_IOPT_TOOLS_NetMarking* avail )
{
    return ( avail->p_2 >= 1 );
}

int t_112_events( TP2_2022_IOPT_TOOLS_InputSignalEvents* events )
{
    return (  1  );
}

int t_112_guards( TP2_2022_IOPT_TOOLS_NetMarking* marking,
                   TP2_2022_IOPT_TOOLS_InputSignals* inputs,
                   TP2_2022_IOPT_TOOLS_PlaceOutputSignals* place_out,
                   TP2_2022_IOPT_TOOLS_EventOutputSignals* ev_out )
{
    return ( inputs->is_Override_Irrigation == 1 );
}

void t_112_remove_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_2--;
}

void t_112_add_marks( TP2_2022_IOPT_TOOLS_NetMarking* marking )
{
    marking->p_12++;
}

void t_112_generate_output_events( TP2_2022_IOPT_TOOLS_OutputSignalEvents* ev_out )
{
    ev_out->oe_Irrigation_On = 1;
}


/* Input event processing: */
void TP2_2022_IOPT_TOOLS_GenerateInputSignalEvents(
        TP2_2022_IOPT_TOOLS_InputSignals *old_values,
        TP2_2022_IOPT_TOOLS_InputSignals *new_values,
        TP2_2022_IOPT_TOOLS_InputSignalEvents *events )
{
    events->ie_Override_Irrigation_On = ( old_values->is_Override_Irrigation<=0 && new_values->is_Override_Irrigation>0 );
    events->ie_Override_Irrigation_Off = ( old_values->is_Override_Irrigation>0 && new_values->is_Override_Irrigation<=0 );
}

/* Output event processing: */
void TP2_2022_IOPT_TOOLS_GenerateEventOutputSignals(
    TP2_2022_IOPT_TOOLS_OutputSignalEvents *events,
    TP2_2022_IOPT_TOOLS_EventOutputSignals *signals )
{
    int new_value;
    new_value = signals->os_Irrigation +events->oe_Irrigation_On -events->oe_Irrigation_Off;
    if( new_value < 0 ) new_value = 0;
    if( new_value > 1 ) new_value = 1;
    signals->os_Irrigation = new_value;
}

/* Transition action processing: */
void TP2_2022_IOPT_TOOLS_GenerateTransitionActionOutputSignals(
    TP2_2022_IOPT_TOOLS_TransitionFiring *tfired,
    TP2_2022_IOPT_TOOLS_NetMarking *marking,
    TP2_2022_IOPT_TOOLS_EventOutputSignals *ev_out )
{
}

/* Place Output Processing */
void TP2_2022_IOPT_TOOLS_GeneratePlaceOutputSignals(
    TP2_2022_IOPT_TOOLS_NetMarking *marking,
    TP2_2022_IOPT_TOOLS_InputSignals *inputs,
    TP2_2022_IOPT_TOOLS_PlaceOutputSignals *place_out,
    TP2_2022_IOPT_TOOLS_EventOutputSignals *ev_out )
{
    int exp_res, new_val, n_writes;
    TP2_2022_IOPT_TOOLS_PlaceOutputSignals new_out = *place_out;
    
    /* Signal os_Irrigation_Duration */
    new_val = 0;
    if( marking->p_7 > 0 ) { /* Place p_Checked */
        exp_res = 0;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_56 > 0 ) { /* Place p_Irrigating */
        exp_res = place_out->os_Irrigation_Duration + 1;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 500 ) new_out.os_Irrigation_Duration = 500;
    else if( new_val < 0 ) new_out.os_Irrigation_Duration = 0;
    else new_out.os_Irrigation_Duration = new_val;

    /* Signal os_Sensor_Check */
    new_val = 0;
    if( marking->p_7 > 0 ) { /* Place p_Checked */
        exp_res = 1;
        if( 1 )
            new_val = exp_res;
    }
    if( marking->p_56 > 0 ) { /* Place p_Irrigating */
        exp_res = place_out->os_Sensor_Check;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( marking->p_12 > 0 ) { /* Place p_Starting_Irrigation */
        exp_res = place_out->os_Sensor_Check;
        if( ABS(exp_res-0) > ABS(new_val-0) )
            new_val = exp_res;
    }
    if( new_val > 1 ) new_out.os_Sensor_Check = 1;
    else if( new_val < 0 ) new_out.os_Sensor_Check = 0;
    else new_out.os_Sensor_Check = new_val;

    *place_out = new_out;
}
